name: 'Build and Publish Docker Image to GitHub Container Registry'
description: 'Build Docker Image from the latest release and pushes it to GitHub Container Registry'
author: 'The Software Development Team at InfoRLife SA <dev@inforlife.ch>'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  container_pat:
    description: 'Personal Access Token to push image to GH Container registry'
    required: true
    default: ''
  rubygems_pat:
    description: 'Personal Access Token to access GH RubyGems registry'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
